# %%
# This class contains functions which
# return a group or list of columns to be imported
# in the jupyter notebook for analysis


class CodeBook:
    def __init__(self):

        self.__cardiovascular = ['site_qc', 'cohort_id_c', 'age', 'sex',
                                 'blood_sugar_qc',
                                 'diabetes_qc',
                                 'diabetes_self_reported_qc',
                                 'diabetes_12months_qc',
                                 'diabetes_treatment_qc',
                                 'diabetes_treat_curr_qc',
                                 'diabetes_treat_insulin_qc',
                                 'diabetes_treat_pills_qc',
                                 'diabetes_treat_diet_qc',
                                 'diabetes_treat_weight_loss_qc',
                                 'diabetes_treat_other_qc',
                                 'diabetes_meds_specify_qc',
                                 'diabetes_traditional_qc',
                                 'diabetes_history_qc',
                                 'mother_diabetes_qc',
                                 'father_diabetes_qc',
                                 'brother_diabetes_qc',
                                 'brother_2_diabetes_qc',
                                 'brother_3_diabetes_qc',
                                 'brother_4_diabetes_qc',
                                 'sister_diabetes_qc',
                                 'sister_2_diabetes_qc',
                                 'sister_3_diabetes_qc',
                                 'sister_4_diabetes_qc',
                                 'son_diabetes_qc',
                                 'son_2_diabetes_qc',
                                 'son_3_diabetes_qc',
                                 'son_4_diabetes_qc',
                                 'daughter_diabetes_qc',
                                 'daughter_2_diabetes_qc',
                                 'daughter_3_diabetes_qc',
                                 'daughter_4_diabetes_qc',
                                 'other_diabetes_qc',
                                 'other_diabetes_specify_qc',
                                 'stroke_qc',
                                 'stroke_diagnosed_qc',
                                 'transient_ischemic_attack_qc',
                                 'weakness_qc',
                                 'numbness_qc',
                                 'blindness_qc',
                                 'half_vision_loss_qc',
                                 'understanding_loss_qc',
                                 'expression_loss_qc',
                                 'bp_measure_qc',
                                 'hypertension_qc',
                                 'hypertension_12months_yn_qc',
                                 'hypertension_treatment_yn_qc',
                                 'hypertension_meds_yn_qc',
                                 'hypertension_meds_qc',
                                 'hypertension_traditional_qc',
                                 'angina_qc',
                                 'angina_treatment_yn_qc',
                                 'angina_treat_now_qc',
                                 'angina_meds_qc',
                                 'angina_traditional_qc',
                                 'pain_qc',
                                 'pain2_qc',
                                 'pain_action_stop_or_slow_qc',
                                 'pain_action_rest_qc',
                                 'pain_action_medicine_qc',
                                 'pain_action_carry_on_qc',
                                 'relief_standstill_qc',
                                 'pain_location_1_qc',
                                 'pain_location_2_qc',
                                 'pain_location_3_qc',
                                 'pain_location_4_qc',
                                 'pain_location_5_qc',
                                 'pain_location_6_qc',
                                 'pain_location_7_qc',
                                 'pain_location_8_qc',
                                 'pain_location_9_qc',
                                 'pain_location_10_qc',
                                 'pain_location_11_qc',
                                 'pain_location_12_qc',
                                 'pain_location_13_qc',
                                 'pain_location_14_qc',
                                 'pain_location_15_qc',
                                 'pain_location_16_qc',
                                 'pain_location_17_qc',
                                 'pain_location_18_qc',
                                 'heartattack_qc',
                                 'heartattack_treatment_qc',
                                 'heartattack_traditional_qc',
                                 'congestive_heart_failure_qc',
                                 'chf_treatment_yn_qc',
                                 'chf_treat_now_qc',
                                 'chf_meds_qc',
                                 'chf_traditional_qc',
                                 'cholesterol_qc',
                                 'h_cholesterol_qc',
                                 'cholesterol_treatment_qc',
                                 'cholesterol_meds_special_diet_qc',
                                 'cholesterol_meds_weight_loss_qc',
                                 'cholesterol_meds_medicine_qc',
                                 'cholesterol_meds_other_qc',
                                 'cholesterol_traditional_qc',
                                 'thyroid_qc',
                                 'thyroid_type_qc',
                                 'thryroid_specify_qc',
                                 'thyroid_treatment_yn_qc',
                                 'thyroid_treatment_hormone_qc',
                                 'thyroid_treatment_surgery_qc',
                                 'thyroid_treatment_iodine_qc',
                                 'thyroid_treatment_drugs_qc',
                                 'parents_thyroid',
                                 'specify_thyroid_parent_qc',
                                 'kidney_disease_qc',
                                 'know_type_kidney_disease_qc',
                                 'type_kidney_disease_qc',
                                 'low_kidney_function_qc',
                                 'kidney_family_qc',
                                 'family_kidney_mother_qc',
                                 'family_kidney_father_qc',
                                 'family_kidney_other_qc',
                                 'family_kidney_other_specify',
                                 'kidney_family_type_qc',
                                 'family_kidney_type_qc',
                                 'site_qc']

        self.__demographic = ['site_qc', 'cohort_id_c', 'age', 'sex',
                              'country_c',
                              'home_language_qc',
                              'ethnicity_qc',
                              'father_ethnicity_qc',
                              'father_language_qc',
                              'pat_gfather_ethnicity_qc',
                              'pat_gfather_language_qc',
                              'pat_gmother_language_qc',
                              'pat_gmother_ethnicity_qc',
                              'mother_ethnicity_qc',
                              'mother_language_qc',
                              'mat_gfather_ethnicity_qc',
                              'mat_gfather_language_qc',
                              'mat_gmother_ethnicity_qc',
                              'mat_gmother_language_qc',
                              'siblings_qc',
                              'number_of_brothers_qc',
                              'number_of_sisters_qc',
                              'children_qc',
                              'number_of_sons_qc',
                              'number_of_daughters_qc']

        self.__lifestyle = ['site_qc', 'cohort_id_c', 'age', 'sex',
                            'tobacco_use_qc',
                            'current_smoker_qc',
                            'what_smoke_cigarettes_qc',
                            'what_smoke_pipe_qc',
                            'what_smoke_hand_rolled_qc',
                            'what_smoke_cigars_qc',
                            'what_smoke_e_cigarettes_qc',
                            'smoking_frequence_qc',
                            'smoke_per_day_qc',
                            'age_start_smoking_qc',
                            'year_stop_smoking_qc',
                            'smokeless_tobacco_use_qc',
                            'snuff_use_qc',
                            'snuff_method_nose_qc',
                            'snuff_method_mouth_qc',
                            'frequence_of_snuff_use_qc',
                            'frequence_of_snuff_use_per_day_qc',
                            'chewing_tobacco_use_qc',
                            'frequence_of_chewing_tobacco_use_qc',
                            'frequence_of_chewing_tobacco_use_per_day_qc',
                            'consume_alcohol_qc',
                            'current_alcohol_consumer_qc',
                            'frequence_of_alcohol_consumption_qc',
                            'amount_of_alcohol_consumed_per_day_qc',
                            'consider_alcohol_cutdown_qc',
                            'criticised_for_drinking_qc',
                            'guilty_for_drinking_qc',
                            'had_hangover_qc',
                            'drinking_past_year_qc',
                            'alcohol_type_consumed_beer_qc',
                            'alcohol_type_consumed_wine_qc',
                            'alcohol_type_consumed_spirits_qc',
                            'alcohol_type_consumed_home_brew_qc',
                            'alcohol_type_consumed_other_qc',
                            'specify_alcohol_type_consumed_qc',
                            'use_drug_qc',
                            'days_fruit_qc',
                            'fruit_servings_qc',
                            'days_veg_qc',
                            'servings_veg_qc',
                            'vendor_meals_qc',
                            'days_bread',
                            'days_bread_qc',
                            'slices_bread_qc',
                            'sugardrinks_qc',
                            'juice',
                            'juice_qc',
                            'change_diet_qc',
                            'lose_weight_qc',
                            'sleep_time_week_qc',
                            'wakeup_time_week_qc',
                            'hours_sleep_week',
                            'sleep_time_weekend_qc',
                            'wakeup_time_weekend_qc',
                            'hours_sleep_weekend']

        self.__heath = ['site_qc', 'cohort_id_c', 'age', 'sex',
                        'breast_cancer_qc',
                        'cervical_cancer_qc',
                        'other_cancers_qc',
                        'asthma_qc',
                        'treatment_gen_health_qc',
                        'medication_qc',
                        'list_medication_qc',
                        'traditional_med_qc']

        self.__family = ['site_qc', 'cohort_id_c', 'age', 'sex',
                         'obesity_mom_qc',
                         'h_blood_pressure_mom_qc',
                         'h_cholesterol_mom_qc',
                         'breast_cancer_mom_qc',
                         'cervical_cancer_mom_qc',
                         'other_cancers_mom_qc',
                         'asthma_mom_qc',
                         'obesity_dad_qc',
                         'h_blood_pressure_dad_qc',
                         'h_cholesterol_dad_qc',
                         'prostate_cancer_dad_qc',
                         'other_cancers_dad_qc',
                         'asthma_dad_qc']

        self.__exposure = ['site_qc',
                           'pesticide_qc',
                           'years_pesticide_qc',
                           'region_pesticide_qc',
                           'pesticide_type_qc',
                           'pesticide_list']

        self.__infection = ['site_qc', 'cohort_id_c', 'age', 'sex',
                            'malaria_qc',
                            'malaria_month_qc',
                            'malaria_area_qc',
                            'tb_qc',
                            'tb_12months_qc',
                            'tb_diagnosed_qc',
                            'tb_treatment_qc',
                            'tb_meds_qc',
                            'tb_counselling_qc',
                            'tb_traditional_med_qc']

        self.__measurements = ['site_qc', 'cohort_id_c', 'age', 'sex',
                               'standing_height_qc',
                               'weight_qc',
                               'waist_circumference_qc',
                               'hip_circumference_qc',
                               'bp_sys_average_qc',
                               'bp_dia_average_qc',
                               'pulse_average_qc',
                               'visceral_fat_qc',
                               'subcutaneous_fat_qc',
                               'min_cimt_right',
                               'max_cimt_right',
                               'mean_cimt_right',
                               'mean_cimt_right_qc',
                               'min_cimt_left',
                               'max_cimt_left',
                               'mean_cimt_left',
                               'mean_cimt_left_qc',
                               'fasting_confirmation_qc',
                               'tested_hiv_qc',
                               'hiv_status_qc',
                               'hiv_positive_qc',
                               'hiv_medication_qc',
                               'traditional_med_hiv_qc',
                               'agree_hivtest',
                               'result_hiv_qc',
                               'glucose_qc',
                               's_creatinine_qc',
                               'insulin_qc',
                               'hdl_qc',
                               'ldl_qc',
                               'cholesterol_1_qc',
                               'triglycerides_qc',
                               'ur_creatinine_qc',
                               'ur_albumin_qc',
                               'ur_protein_qc']

        self.__calculatedCols = ['site_qc', 'cohort_id_c', 'age', 'sex',
                                 'residence_c_qc',
                                 'number_of_siblings_c',
                                 'number_of_children_c',
                                 'years_education_c_qc',
                                 'smoking_status_c_qc',
                                 'smoking_frequence_c_qc',
                                 'smoking_grade_c_qc',
                                 'alcohol_status_c_qc',
                                 'alcohol_use_status_c_qc',
                                 'alcohol_consumption_frequence_c_qc',
                                 'alcohol_grade_c_qc',
                                 'avg_sleep_per_night_c',
                                 'mvpa_c',
                                 'mvpa_cat_c',
                                 'exercise_duration_c_qc',
                                 'exercise_status_c_qc',
                                 'exercise_freq_c_qc',
                                 'diet_veg_freq_c_qc',
                                 'diet_veg_qty_c',
                                 'diet_fruit_freq_c_qc',
                                 'diet_fruit_qty_c',
                                 'diet_health_c_qc',
                                 'dm_present_c',
                                 'diabetes_status_c_qc',
                                 'htn_present_c',
                                 'htn_jnc7_qc',
                                 'cancer_status_c_qc',
                                 'bmi_c_qc',
                                 'bmi_cat_c_qc',
                                 'waist_hip_r_c_qc',
                                 'hiv_final_status_c',
                                 'acr_qc',
                                 'non_hdl_c_c_qc',
                                 'dyslipidemia_c',
                                 'e_grf_c',
                                 'ckd_c']

        self.__requested = ['site_qc', 'cohort_id_c', 'age', 'hiv_final_status_c']


    def get_cardiovascular_cols(self):
        return self.__cardiovascular

    def get_demographic_cols(self):
        return self.__demographic

    def get_lifestyle_cols(self):
        return self.__lifestyle

    def get_health_cols(self):
        return self.__heath

    def get_family_history_cols(self):
        return self.__family

    def get_exposure_cols(self):
        return self.__exposure

    def get_infections_cols(self):
        return self.__infection

    def get_measurements_cols(self):
        return self.__measurements

    def get_calculated_cols(self):
        return self.__calculatedCols

    def get_requested(self):
        return self.__requested
